# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'full_offical.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataDisplay(object):
    def setupUi(self, DataDisplay):
        DataDisplay.setObjectName("DataDisplay")
        DataDisplay.resize(475, 322)
        font = QtGui.QFont()
        font.setKerning(True)
        DataDisplay.setFont(font)
        DataDisplay.setWindowTitle("Data display")
        self.centralwidget = QtWidgets.QWidget(DataDisplay)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(-200, 590, 300, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 0, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("50.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 0, 171, 31))
        font = QtGui.QFont()
        font.setFamily("UTM Bebas")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.Vietnamese, QtCore.QLocale.Vietnam))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("UTM Bebas")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.Vietnamese, QtCore.QLocale.Vietnam))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 67, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 250, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 230, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(70, 76, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 200, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(250, 76, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(290, 200, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(150, 116, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(150, 130, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(370, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(370, 130, 67, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(370, 230, 67, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(280, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(150, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(150, 230, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 80, 371, 25))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 170, 67, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 200, 181, 21))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(210, 110, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(210, 130, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(430, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(430, 130, 67, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(430, 230, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(210, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(210, 230, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(280, 200, 181, 21))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 270, 89, 25))
        self.pushButton.setObjectName("pushButton")
        DataDisplay.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DataDisplay)
        self.statusbar.setObjectName("statusbar")
        DataDisplay.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(DataDisplay)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(DataDisplay)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(DataDisplay)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(DataDisplay)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(DataDisplay)
        self.actionPaste.setObjectName("actionPaste")

        self.retranslateUi(DataDisplay)
        QtCore.QMetaObject.connectSlotsByName(DataDisplay)

    def retranslateUi(self, DataDisplay):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("DataDisplay", "Light"))
        self.label_2.setText(_translate("DataDisplay", "Pressure"))
        self.label_5.setText(_translate("DataDisplay", "<html><head/><body><p><span style=\" color:#0055ff;\">TRƯỜNG ĐẠI HỌC BÁCH KHOA</span></p></body></html>"))
        self.label_6.setText(_translate("DataDisplay", "<html><head/><body><p><span style=\" color:#0055ff;\">ĐẠI HỌC QUỐC GIA TP.HCM</span></p></body></html>"))
        self.label_3.setText(_translate("DataDisplay", "Temperature"))
        self.label_7.setText(_translate("DataDisplay", "Humidity"))
        self.label_8.setText(_translate("DataDisplay", "<html><head/><body><p><span style=\" font-weight:600; color:#729fcf;\">CC2538</span></p></body></html>"))
        self.label_10.setText(_translate("DataDisplay", "Humidity"))
        self.label_11.setText(_translate("DataDisplay", "Temperature"))
        self.label_12.setText(_translate("DataDisplay", "ID:  "))
        self.label_13.setText(_translate("DataDisplay", "ID"))
        self.label_16.setText(_translate("DataDisplay", "Last updated :"))
        self.label_17.setText(_translate("DataDisplay", "ID"))
        self.label_18.setText(_translate("DataDisplay", "C"))
        self.label_19.setText(_translate("DataDisplay", "RH"))
        self.label_20.setText(_translate("DataDisplay", "Lux"))
        self.label_21.setText(_translate("DataDisplay", "hPa"))
        self.label_22.setText(_translate("DataDisplay", "Lux"))
        self.label_23.setText(_translate("DataDisplay", "Light"))
        self.label_24.setText(_translate("DataDisplay", "RH"))
        self.label_25.setText(_translate("DataDisplay", "C"))
        self.label_9.setText(_translate("DataDisplay", "<html><head/><body><p><span style=\" font-weight:600; color:#729fcf;\">ESP8266</span></p></body></html>"))
        self.label_26.setText(_translate("DataDisplay", "ºC"))
        self.label_27.setText(_translate("DataDisplay", "RH"))
        self.label_28.setText(_translate("DataDisplay", "lux"))
        self.label_29.setText(_translate("DataDisplay", "hP"))
        self.label_30.setText(_translate("DataDisplay", "lux"))
        self.label_31.setText(_translate("DataDisplay", "RH"))
        self.label_32.setText(_translate("DataDisplay", "ºC"))
        self.pushButton.setText(_translate("DataDisplay", "Exit"))
        self.actionNew.setText(_translate("DataDisplay", "New"))
        self.actionOpen.setText(_translate("DataDisplay", "Open"))
        self.actionSave.setText(_translate("DataDisplay", "Save"))
        self.actionCopy.setText(_translate("DataDisplay", "Copy"))
        self.actionPaste.setText(_translate("DataDisplay", "Paste"))

# import py_rc
